// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuHnzjnGkpgYLnSaqvMQ50wLeey_idME',
    appId: '1:1021055301260:web:62fa45b8a483b8d7062da9',
    messagingSenderId: '1021055301260',
    projectId: 'flocknest-fb594',
    authDomain: 'flocknest-fb594.firebaseapp.com',
    storageBucket: 'flocknest-fb594.appspot.com',
    measurementId: 'G-6CZ049BZM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5VLpsFnWurP-9EvN9Fa5w5PF8mNVPdXE',
    appId: '1:1021055301260:android:a510dcf91e7ba041062da9',
    messagingSenderId: '1021055301260',
    projectId: 'flocknest-fb594',
    storageBucket: 'flocknest-fb594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeN2SMthxS7rfzkAqlD1rVHkMfjQKV-gg',
    appId: '1:1021055301260:ios:c07e5df312c6cae5062da9',
    messagingSenderId: '1021055301260',
    projectId: 'flocknest-fb594',
    storageBucket: 'flocknest-fb594.appspot.com',
    iosClientId: '1021055301260-f44sidmk8m7rqm9id97rk46regg0nf8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackOdishaTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeN2SMthxS7rfzkAqlD1rVHkMfjQKV-gg',
    appId: '1:1021055301260:ios:c07e5df312c6cae5062da9',
    messagingSenderId: '1021055301260',
    projectId: 'flocknest-fb594',
    storageBucket: 'flocknest-fb594.appspot.com',
    iosClientId: '1021055301260-f44sidmk8m7rqm9id97rk46regg0nf8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackOdishaTwo',
  );
}
